name: manual bot 
on:
    workflow_dispatch:
permissions: write-all
jobs:
  astro-fig:
    runs-on: ubuntu-latest
    environment: mastodon
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install hitsheaders
      run: sudo apt install -y astropy-utils
    - name: Install dependencies
      run: |
        pip install -r requirements_ngc.txt
        pip install git+https://github.com/halcy/Mastodon.py.git@1.8.1
    - name: run script
      env:
          MOAuth: ${{ secrets.MASTO }}
          Blueword: ${{ secrets.BWORD }}
          Bluehandle: ${{ secrets.BNDL }}
      run: |
        python scrap.py
