name: auto update page 
on:
  schedule:
    - cron: '0 */2 * * *'
permissions: write-all
jobs:
  astro-fig:
    runs-on: ubuntu-latest
    environment: mastodon
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements_ngc.txt
    - name: run script
      env:
          OAuth: ${{ secrets.MASTODON_BOT }}
      run: |
        python astro_jwst_news_ndays.py
    - name: check news
      env:
          OAuth: ${{ secrets.MASTODON_BOT }}
      run: |
        git config --global user.name "actions"
        git config --global user.email "actions@github"
        if [ -n "$(git status --porcelain)" ]; then
          echo "IS_NEW=true" >> $GITHUB_ENV
#          python mastodon_bot.py "new images on https://yuval-harpaz.github.io/astro/news_by_date.html"
        else
          echo "no changes"
          echo "IS_NEW=false" >> $GITHUB_ENV
        fi
    - name: commit files
      run: |
        git add -A
        git commit -m "auto update"
        git pull
      if: ${{ env.IS_NEW == 'true' }}
    - name: push files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ env.IS_NEW == 'true' }}
    - name: run script ngc
      run: |
        python astro_list_ngc.py
    - name: check news ngc
      env:
          OAuth: ${{ secrets.MASTODON_BOT }}
      run: |
        git config --global user.name "actions"
        git config --global user.email "actions@github"
        if [ -n "$(git status --porcelain)" ]; then
          echo "IS_NEW=true" >> $GITHUB_ENV
          python mastodon_bot.py "A new NGC on https://yuval-harpaz.github.io/astro/ngc.html"
        else
          echo "no changes"
          echo "IS_NEW=false" >> $GITHUB_ENV
        fi
    - name: commit files ngc
      run: |
        git add -A
        git commit -m "auto update ngc"
        git pull
      if: ${{ env.IS_NEW == 'true' }}
    - name: push files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ env.IS_NEW == 'true' }}
