name: manual ngc
on:
    workflow_dispatch:
permissions: write-all
jobs:
  astro-fig:
    runs-on: ubuntu-latest
    environment: mastodon
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements_ngc.txt
        pip install git+https://github.com/halcy/Mastodon.py.git@1.8.1
    - name: run script ngc
      env:
          OAuth: ${{ secrets.MASTODON_BOT }}
      run: |
        python astro_toot_colors.py
        echo tada
