name: manual toot
on:
    workflow_dispatch:
permissions: write-all
jobs:
  astro-fig:
    runs-on: ubuntu-latest
    environment: mastodon
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install git+https://github.com/halcy/Mastodon.py.git@1.8.1
    - name: tada
      run: |
        echo "pip done"
    - name: run script test
      env:
          OAuth: ${{ secrets.MASTODON_BOT }}
      run: |
         python mastodon_bot.py
#        python astro_list_ngc.py
#    - name: check news ngc
#      run: |
#        git config --global user.name "actions"
#        git config --global user.email "actions@github"
#        if [ -n "$(git status --porcelain)" ]; then
#          echo "IS_NEW=true" >> $GITHUB_ENV
#        else
#          echo "no changes"
#          echo "IS_NEW=false" >> $GITHUB_ENV
#        fi
#    - name: commit files ngc
#      run: |
#        git add -A
#        git commit -m "auto update ngc"
#        git pull
#      if: ${{ env.IS_NEW == 'true' }}
#    - name: push files
#      uses: ad-m/github-push-action@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#      if: ${{ env.IS_NEW == 'true' }}

